### ISSUE TITLE
Unexpected token ':' in Angular Project

### ISSUE THREAD

**Issue by agholipour** [soccerloway/quill-better-table#82]
Hi I am receiving the following error when the angular app starts

Uncaught SyntaxError: Unexpected token ':'
    at Object../node_modules/quill-delta/dist/Op.js (:4200/vendor.js:61536:9)
    at __nested_webpack_require_732__ (:4200/vendor.js:59021:27)
    at eval (webpack://Quill/./node_modules/quill-delta/dist/Delta.js?:9:28)
    at Object../node_modules/quill-delta/dist/Delta.js (:4200/vendor.js:61504:9)
    at __nested_webpack_require_732__ (:4200/vendor.js:59021:27)
    at eval (webpack://Quill/./core/quill.js?:6:69)
    at Module../core/quill.js (:4200/vendor.js:59876:9)
    at __nested_webpack_require_732__ (:4200/vendor.js:59021:27)
    at eval (webpack://Quill/./core.js?:2:69)
    at Module../core.js (:4200/vendor.js:59780:9)

 "dependencies": {
    "ngx-quill": "^16.1.1",
     "quill": "^2.0.0-dev.4",
    "quill-better-table": "^1.2.10",
    "@angular/cli": "^13.0.3",
    "@angular/core": "^13.0.2",
       .....
    }
how can I fix this ? Thanks

**Comment by agholipour** [comment]
I downgraded angular to version 12 and now it is working,

**Comment by sergiuwaxmann** [comment]
@agholipour

Can you share your `package.json`? I downgraded to version 12.2.0 but I still have this issue...
